// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: template/Account.proto

package com.cyou.fusion.example.protocol;

public final class Account {
  private Account() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface P_ACCOUNT_LOGIN_REQOrBuilder extends
      // @@protoc_insertion_point(interface_extends:P_ACCOUNT_LOGIN_REQ)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string token = 1;</code>
     */
    boolean hasToken();
    /**
     * <code>required string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <code>required string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code P_ACCOUNT_LOGIN_REQ}
   */
  public static final class P_ACCOUNT_LOGIN_REQ extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:P_ACCOUNT_LOGIN_REQ)
      P_ACCOUNT_LOGIN_REQOrBuilder {
    // Use P_ACCOUNT_LOGIN_REQ.newBuilder() to construct.
    private P_ACCOUNT_LOGIN_REQ(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private P_ACCOUNT_LOGIN_REQ(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final P_ACCOUNT_LOGIN_REQ defaultInstance;
    public static P_ACCOUNT_LOGIN_REQ getDefaultInstance() {
      return defaultInstance;
    }

    public P_ACCOUNT_LOGIN_REQ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private P_ACCOUNT_LOGIN_REQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              token_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cyou.fusion.example.protocol.Account.internal_static_P_ACCOUNT_LOGIN_REQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cyou.fusion.example.protocol.Account.internal_static_P_ACCOUNT_LOGIN_REQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ.class, com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ.Builder.class);
    }

    public static com.google.protobuf.Parser<P_ACCOUNT_LOGIN_REQ> PARSER =
        new com.google.protobuf.AbstractParser<P_ACCOUNT_LOGIN_REQ>() {
      public P_ACCOUNT_LOGIN_REQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new P_ACCOUNT_LOGIN_REQ(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<P_ACCOUNT_LOGIN_REQ> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private java.lang.Object token_;
    /**
     * <code>required string token = 1;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      token_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTokenBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTokenBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code P_ACCOUNT_LOGIN_REQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:P_ACCOUNT_LOGIN_REQ)
        com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cyou.fusion.example.protocol.Account.internal_static_P_ACCOUNT_LOGIN_REQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cyou.fusion.example.protocol.Account.internal_static_P_ACCOUNT_LOGIN_REQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ.class, com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ.Builder.class);
      }

      // Construct using com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cyou.fusion.example.protocol.Account.internal_static_P_ACCOUNT_LOGIN_REQ_descriptor;
      }

      public com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ getDefaultInstanceForType() {
        return com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ.getDefaultInstance();
      }

      public com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ build() {
        com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ buildPartial() {
        com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ result = new com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ) {
          return mergeFrom((com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ other) {
        if (other == com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ.getDefaultInstance()) return this;
        if (other.hasToken()) {
          bitField0_ |= 0x00000001;
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasToken()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_REQ) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object token_ = "";
      /**
       * <code>required string token = 1;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:P_ACCOUNT_LOGIN_REQ)
    }

    static {
      defaultInstance = new P_ACCOUNT_LOGIN_REQ(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:P_ACCOUNT_LOGIN_REQ)
  }

  public interface P_ACCOUNT_LOGIN_RESOrBuilder extends
      // @@protoc_insertion_point(interface_extends:P_ACCOUNT_LOGIN_RES)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required bool result = 1;</code>
     */
    boolean getResult();
  }
  /**
   * Protobuf type {@code P_ACCOUNT_LOGIN_RES}
   */
  public static final class P_ACCOUNT_LOGIN_RES extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:P_ACCOUNT_LOGIN_RES)
      P_ACCOUNT_LOGIN_RESOrBuilder {
    // Use P_ACCOUNT_LOGIN_RES.newBuilder() to construct.
    private P_ACCOUNT_LOGIN_RES(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private P_ACCOUNT_LOGIN_RES(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final P_ACCOUNT_LOGIN_RES defaultInstance;
    public static P_ACCOUNT_LOGIN_RES getDefaultInstance() {
      return defaultInstance;
    }

    public P_ACCOUNT_LOGIN_RES getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private P_ACCOUNT_LOGIN_RES(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cyou.fusion.example.protocol.Account.internal_static_P_ACCOUNT_LOGIN_RES_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cyou.fusion.example.protocol.Account.internal_static_P_ACCOUNT_LOGIN_RES_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES.class, com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES.Builder.class);
    }

    public static com.google.protobuf.Parser<P_ACCOUNT_LOGIN_RES> PARSER =
        new com.google.protobuf.AbstractParser<P_ACCOUNT_LOGIN_RES>() {
      public P_ACCOUNT_LOGIN_RES parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new P_ACCOUNT_LOGIN_RES(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<P_ACCOUNT_LOGIN_RES> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean result_;
    /**
     * <code>required bool result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool result = 1;</code>
     */
    public boolean getResult() {
      return result_;
    }

    private void initFields() {
      result_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code P_ACCOUNT_LOGIN_RES}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:P_ACCOUNT_LOGIN_RES)
        com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RESOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cyou.fusion.example.protocol.Account.internal_static_P_ACCOUNT_LOGIN_RES_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cyou.fusion.example.protocol.Account.internal_static_P_ACCOUNT_LOGIN_RES_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES.class, com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES.Builder.class);
      }

      // Construct using com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cyou.fusion.example.protocol.Account.internal_static_P_ACCOUNT_LOGIN_RES_descriptor;
      }

      public com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES getDefaultInstanceForType() {
        return com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES.getDefaultInstance();
      }

      public com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES build() {
        com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES buildPartial() {
        com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES result = new com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES) {
          return mergeFrom((com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES other) {
        if (other == com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cyou.fusion.example.protocol.Account.P_ACCOUNT_LOGIN_RES) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean result_ ;
      /**
       * <code>required bool result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool result = 1;</code>
       */
      public boolean getResult() {
        return result_;
      }
      /**
       * <code>required bool result = 1;</code>
       */
      public Builder setResult(boolean value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:P_ACCOUNT_LOGIN_RES)
    }

    static {
      defaultInstance = new P_ACCOUNT_LOGIN_RES(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:P_ACCOUNT_LOGIN_RES)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_P_ACCOUNT_LOGIN_REQ_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_P_ACCOUNT_LOGIN_REQ_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_P_ACCOUNT_LOGIN_RES_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_P_ACCOUNT_LOGIN_RES_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026template/Account.proto\"$\n\023P_ACCOUNT_LO" +
      "GIN_REQ\022\r\n\005token\030\001 \002(\t\"%\n\023P_ACCOUNT_LOGI" +
      "N_RES\022\016\n\006result\030\001 \002(\010B+\n com.cyou.fusion" +
      ".example.protocolB\007Account"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_P_ACCOUNT_LOGIN_REQ_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_P_ACCOUNT_LOGIN_REQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_P_ACCOUNT_LOGIN_REQ_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_P_ACCOUNT_LOGIN_RES_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_P_ACCOUNT_LOGIN_RES_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_P_ACCOUNT_LOGIN_RES_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
