// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: template/Role.proto

package com.cyou.fusion.example.protocol;

public final class Role {
  private Role() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface P_ROLE_INFO_REQOrBuilder extends
      // @@protoc_insertion_point(interface_extends:P_ROLE_INFO_REQ)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 level = 3;</code>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 3;</code>
     */
    int getLevel();

    /**
     * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
     */
    java.util.List<com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ>
        getItemList();
    /**
     * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
     */
    com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ getItem(int index);
    /**
     * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
     */
    int getItemCount();
    /**
     * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
     */
    java.util.List<? extends com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQOrBuilder>
        getItemOrBuilderList();
    /**
     * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
     */
    com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQOrBuilder getItemOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code P_ROLE_INFO_REQ}
   */
  public static final class P_ROLE_INFO_REQ extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:P_ROLE_INFO_REQ)
      P_ROLE_INFO_REQOrBuilder {
    // Use P_ROLE_INFO_REQ.newBuilder() to construct.
    private P_ROLE_INFO_REQ(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private P_ROLE_INFO_REQ(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final P_ROLE_INFO_REQ defaultInstance;
    public static P_ROLE_INFO_REQ getDefaultInstance() {
      return defaultInstance;
    }

    public P_ROLE_INFO_REQ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private P_ROLE_INFO_REQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              level_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                item_ = new java.util.ArrayList<com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ>();
                mutable_bitField0_ |= 0x00000008;
              }
              item_.add(input.readMessage(com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          item_ = java.util.Collections.unmodifiableList(item_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cyou.fusion.example.protocol.Role.internal_static_P_ROLE_INFO_REQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cyou.fusion.example.protocol.Role.internal_static_P_ROLE_INFO_REQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ.class, com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ.Builder.class);
    }

    public static com.google.protobuf.Parser<P_ROLE_INFO_REQ> PARSER =
        new com.google.protobuf.AbstractParser<P_ROLE_INFO_REQ>() {
      public P_ROLE_INFO_REQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new P_ROLE_INFO_REQ(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<P_ROLE_INFO_REQ> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    /**
     * <code>required int32 level = 3;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 level = 3;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int ITEM_FIELD_NUMBER = 4;
    private java.util.List<com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ> item_;
    /**
     * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
     */
    public java.util.List<com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ> getItemList() {
      return item_;
    }
    /**
     * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
     */
    public java.util.List<? extends com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQOrBuilder>
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
     */
    public com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
     */
    public com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      level_ = 0;
      item_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getItemCount(); i++) {
        if (!getItem(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, level_);
      }
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(4, item_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, level_);
      }
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, item_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code P_ROLE_INFO_REQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:P_ROLE_INFO_REQ)
        com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cyou.fusion.example.protocol.Role.internal_static_P_ROLE_INFO_REQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cyou.fusion.example.protocol.Role.internal_static_P_ROLE_INFO_REQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ.class, com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ.Builder.class);
      }

      // Construct using com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          itemBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cyou.fusion.example.protocol.Role.internal_static_P_ROLE_INFO_REQ_descriptor;
      }

      public com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ getDefaultInstanceForType() {
        return com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ.getDefaultInstance();
      }

      public com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ build() {
        com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ buildPartial() {
        com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ result = new com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.level_ = level_;
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            item_ = java.util.Collections.unmodifiableList(item_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ) {
          return mergeFrom((com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ other) {
        if (other == com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (itemBuilder_ == null) {
          if (!other.item_.isEmpty()) {
            if (item_.isEmpty()) {
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureItemIsMutable();
              item_.addAll(other.item_);
            }
            onChanged();
          }
        } else {
          if (!other.item_.isEmpty()) {
            if (itemBuilder_.isEmpty()) {
              itemBuilder_.dispose();
              itemBuilder_ = null;
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000008);
              itemBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemFieldBuilder() : null;
            } else {
              itemBuilder_.addAllMessages(other.item_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        for (int i = 0; i < getItemCount(); i++) {
          if (!getItem(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cyou.fusion.example.protocol.Role.P_ROLE_INFO_REQ) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>required int32 level = 3;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 level = 3;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 3;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000004;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 3;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ> item_ =
        java.util.Collections.emptyList();
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          item_ = new java.util.ArrayList<com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ>(item_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ, com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.Builder, com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQOrBuilder> itemBuilder_;

      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public java.util.List<com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ> getItemList() {
        if (itemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(item_);
        } else {
          return itemBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public int getItemCount() {
        if (itemBuilder_ == null) {
          return item_.size();
        } else {
          return itemBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ getItem(int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);
        } else {
          return itemBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public Builder setItem(
          int index, com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.set(index, value);
          onChanged();
        } else {
          itemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public Builder setItem(
          int index, com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public Builder addItem(com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(value);
          onChanged();
        } else {
          itemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public Builder addItem(
          int index, com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(index, value);
          onChanged();
        } else {
          itemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public Builder addItem(
          com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public Builder addItem(
          int index, com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public Builder addAllItem(
          java.lang.Iterable<? extends com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ> values) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, item_);
          onChanged();
        } else {
          itemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public Builder removeItem(int index) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.remove(index);
          onChanged();
        } else {
          itemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.Builder getItemBuilder(
          int index) {
        return getItemFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQOrBuilder getItemOrBuilder(
          int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);  } else {
          return itemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public java.util.List<? extends com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQOrBuilder>
           getItemOrBuilderList() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(item_);
        }
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.Builder addItemBuilder() {
        return getItemFieldBuilder().addBuilder(
            com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.getDefaultInstance());
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.Builder addItemBuilder(
          int index) {
        return getItemFieldBuilder().addBuilder(
            index, com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.getDefaultInstance());
      }
      /**
       * <code>repeated .P_ITEM_INFO_REQ item = 4;</code>
       */
      public java.util.List<com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.Builder>
           getItemBuilderList() {
        return getItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ, com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.Builder, com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQOrBuilder>
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ, com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.Builder, com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQOrBuilder>(
                  item_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:P_ROLE_INFO_REQ)
    }

    static {
      defaultInstance = new P_ROLE_INFO_REQ(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:P_ROLE_INFO_REQ)
  }

  public interface P_ITEM_INFO_REQOrBuilder extends
      // @@protoc_insertion_point(interface_extends:P_ITEM_INFO_REQ)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 num = 3;</code>
     */
    boolean hasNum();
    /**
     * <code>required int32 num = 3;</code>
     */
    int getNum();
  }
  /**
   * Protobuf type {@code P_ITEM_INFO_REQ}
   */
  public static final class P_ITEM_INFO_REQ extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:P_ITEM_INFO_REQ)
      P_ITEM_INFO_REQOrBuilder {
    // Use P_ITEM_INFO_REQ.newBuilder() to construct.
    private P_ITEM_INFO_REQ(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private P_ITEM_INFO_REQ(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final P_ITEM_INFO_REQ defaultInstance;
    public static P_ITEM_INFO_REQ getDefaultInstance() {
      return defaultInstance;
    }

    public P_ITEM_INFO_REQ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private P_ITEM_INFO_REQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              num_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cyou.fusion.example.protocol.Role.internal_static_P_ITEM_INFO_REQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cyou.fusion.example.protocol.Role.internal_static_P_ITEM_INFO_REQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.class, com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.Builder.class);
    }

    public static com.google.protobuf.Parser<P_ITEM_INFO_REQ> PARSER =
        new com.google.protobuf.AbstractParser<P_ITEM_INFO_REQ>() {
      public P_ITEM_INFO_REQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new P_ITEM_INFO_REQ(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<P_ITEM_INFO_REQ> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUM_FIELD_NUMBER = 3;
    private int num_;
    /**
     * <code>required int32 num = 3;</code>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 num = 3;</code>
     */
    public int getNum() {
      return num_;
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      num_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, num_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, num_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code P_ITEM_INFO_REQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:P_ITEM_INFO_REQ)
        com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cyou.fusion.example.protocol.Role.internal_static_P_ITEM_INFO_REQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cyou.fusion.example.protocol.Role.internal_static_P_ITEM_INFO_REQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.class, com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.Builder.class);
      }

      // Construct using com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cyou.fusion.example.protocol.Role.internal_static_P_ITEM_INFO_REQ_descriptor;
      }

      public com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ getDefaultInstanceForType() {
        return com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.getDefaultInstance();
      }

      public com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ build() {
        com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ buildPartial() {
        com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ result = new com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.num_ = num_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ) {
          return mergeFrom((com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ other) {
        if (other == com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cyou.fusion.example.protocol.Role.P_ITEM_INFO_REQ) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int num_ ;
      /**
       * <code>required int32 num = 3;</code>
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 num = 3;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>required int32 num = 3;</code>
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000004;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 num = 3;</code>
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        num_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:P_ITEM_INFO_REQ)
    }

    static {
      defaultInstance = new P_ITEM_INFO_REQ(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:P_ITEM_INFO_REQ)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_P_ROLE_INFO_REQ_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_P_ROLE_INFO_REQ_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_P_ITEM_INFO_REQ_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_P_ITEM_INFO_REQ_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023template/Role.proto\"Z\n\017P_ROLE_INFO_REQ" +
      "\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\r\n\005level\030\003 \002(" +
      "\005\022\036\n\004item\030\004 \003(\0132\020.P_ITEM_INFO_REQ\"8\n\017P_I" +
      "TEM_INFO_REQ\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\013" +
      "\n\003num\030\003 \002(\005B(\n com.cyou.fusion.example.p" +
      "rotocolB\004Role"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_P_ROLE_INFO_REQ_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_P_ROLE_INFO_REQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_P_ROLE_INFO_REQ_descriptor,
        new java.lang.String[] { "Id", "Name", "Level", "Item", });
    internal_static_P_ITEM_INFO_REQ_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_P_ITEM_INFO_REQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_P_ITEM_INFO_REQ_descriptor,
        new java.lang.String[] { "Id", "Name", "Num", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
